apiVersion: rhdh.redhat.com/v1alpha1
kind: Backstage
metadata:
  name: developer-hub
spec:
  application:
    dynamicPluginsConfigMapName: dynamic-plugins-rhdh
    appConfig:
      mountPath: /opt/app-root/src
      configMaps:
      - name: app-config-rhdh      
    extraFiles:
      mountPath: /opt/app-root/src
    extraEnvs:
      secrets:
        - name: gitlab-secrets
        - name: rhdh-secrets               
    replicas: 1
    route:
      enabled: true
  database:
    enableLocalDb: true
